ORDER_POSITIVE_REWARD = 10
ORDER_NEGATIVE_REWARD = -100
STORE_POSITIVE_REWARD = 10
STORE_NEGATIVE_REWARD = -10
DELIVER_POSITIVE_REWARD = 100
DELIVER_NEGATIVE_REWARD = -100
REQUEST_EXPIRED_REWARD = -50
INVENTORY_COST_FACTOR = 10
