ORDER_POSITIVE_REWARD = 5
ORDER_NEGATIVE_REWARD = -25
STORE_POSITIVE_REWARD = 5
STORE_NEGATIVE_REWARD = -10
DELIVER_POSITIVE_REWARD = 100
DELIVER_NEGATIVE_REWARD = -100
REQUEST_EXPIRED_REWARD = -100
INVENTORY_COST_FACTOR = 10
